---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: geo-app
  template:
    metadata:
      labels:
        app: geo-app
    spec:
      containers:
      - name: geo-app-container
        image: theoalban/geoapp:39

---
apiVersion: v1
kind: Service
metadata:
  name: geo-app-service
spec:
  type: NodePort
  selector:
    app: geo-app
  ports:
    - port: 8082
      protocol: TCP
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8082
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30009